### PR TITLE
Improve commands test coverage

### PR DESCRIPTION
**Pull request by tzuennn**
Added tests for VolunteerAddDateCommand and VolunteerRemoveDateCommand

### CODE REVIEW

**Review by JovenSoh — DISMISSED** [review]
Just curious, why was the access modifier taken out?

**Comment by tzuennn** [comment]
> Just curious, why was the access modifier taken out?

The test file needed to access that variable, so i set it to package private

**Comment by tzuennn** [comment]
Updated it to be package private instead

**Review by Fluffykan — APPROVED** [review]
LGTM

**Pull request merged**
